#!/bin/sh

[ -x /usr/bin/gpioset ] || exit 0

case "$1" in
  start)
	/usr/bin/gpioset 0 166=1
	;;
  stop)
	;;
  restart|reload)
	$0" stop
	$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
