#!/bin/sh
#
# wlan0        Starts WiFi.
#

start() {
        printf "Starting WiFi: "
        #ifconfig wlan0 up
        wpa_supplicant -D nl80211 -i wlan0 -c /etc/wpa_supplicant.conf -B
        udhcpc -i wlan0
        echo "OK"
}
stop() {
        printf "Stopping WiFi: "
        killall udhcpc
        killall wpa_supplicant
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?