#!/bin/sh

start() {
	printf "Starting USB gadget: "
	modprobe libcomposite
	test -e /sys/kernel/config/usb_gadget || mount -t configfs none /sys/kernel/config
	cd /sys/kernel/config/usb_gadget
	mkdir mygadget
	cd mygadget
	echo 0x1209 > idVendor
	echo 0x0001 > idProduct
	mkdir strings/0x409
	echo 1234567890 > strings/0x409/serialnumber
	echo TestManufactuer > strings/0x409/manufacturer
	echo TestProduct > strings/0x409/product
	mkdir configs/myconfig.1
	mkdir configs/myconfig.1/strings/0x409
	echo TestConfiguration > configs/myconfig.1/strings/0x409/configuration
	mkdir functions/ecm.1
	echo 4a:75:23:f9:b3:4c > functions/ecm.1/dev_addr
	echo 4a:75:23:f9:b2:4c > functions/ecm.1/host_addr
	ln -s functions/ecm.1 configs/myconfig.1
	echo musb-hdrc.2.auto > UDC
	ip link set up usb0
	ip addr add 192.168.99.1/24 dev usb0
        echo "OK"
}

stop() {
	printf "Stopping USB gadget: "
	cd /sys/kernel/config/usb_gadget/mygadget
	ip link set down usb0
	ip addr del 192.168.99.1/24 dev usb0
	echo "" > UDC
	rm configs/myconfig.1/ecm.1
	rmdir configs/myconfig.1/strings/0x409
	rmdir configs/myconfig.1
	rmdir functions/ecm.1
	rmdir strings/0x409
	cd ..
	rmdir mygadget
	rmmod usb_f_ecm
	rmmod u_ether
	rmmod libcomposite
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
