#!/bin/sh

#
# Fixes up var for a read-only FS
#

start() {
	mkdir -p /var
	mount -t tmpfs none /var
	mkdir -p /var/run
	mkdir -p /var/dropbear
	rm -r /etc/dropbear
	ln -s /var/dropbear /etc/dropbear
}
stop() {
	true
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?


