#!/bin/sh

[ -x /usr/bin/amixer ] || exit 0

case "$1" in
  start)
	/usr/bin/amixer -c 0 set Headphone 100% unmute
	;;
  stop)
	;;
  restart|reload)
	$0" stop
	$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
