#!/bin/sh

if $(dmesg | grep -q ES-T113-NANO-EMMC); then
    DIR="sun8i-t113-nano-emmc"
elif $(dmesg | grep -q ES-T113-NANO-NAND); then
    DIR="sun8i-t113-nano-nand"
elif $(dmesg | grep -q ES-T113-NANO-LV-EMMC); then
    DIR="sun8i-t113-nano-lv-emmc"
elif $(dmesg | grep -q ES-T113-NANO-LV-NAND); then
    DIR="sun8i-t113-nano-lv-nand"
else
    DIR="unknown"
fi

mount /dev/$MDEV /mnt

if [ -f /mnt/$DIR/autorun.sh ]; then
  /bin/sh /mnt/$DIR/autorun.sh
fi
